name: cooljeanius/osxbom
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: "./configure && make && make check && make distcheck"
    strategy:
      matrix:
        compiler:
        - clang
        - gcc
        os:
        - ubuntu-latest
        - macos-latest
